# Generated by Django 4.0.2 on 2022-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bonus_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
